services:
  www-parcerisa-xyz-minecraft:
    image: docker.parcerisa.xyz:5000/www-parcerisa-xyz-minecraft:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    ports:
      - "3004:3004"
    volumes:
      - "/mnt/hdd2/mcuserLTS/minecraft_backups:/backups"
      - "/home/mcuser/Home-MC/minecraft/1.19_Vanilla_2023:/server"
